config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'tasks#index'
  resources :tasks, only: [:index, :create, :update, :destroy] do
    resources :comments, only: :create
  end
  post 'mark_as_done/:id', to: 'tasks#mark_as_done', as: 'mark_as_done'
  post 'mark_as_cancelled/:id', to: 'tasks#mark_as_cancelled', as: 'mark_as_cancelled'
  post 'mark_as_todo/:id', to: 'tasks#mark_as_todo', as: 'mark_as_todo'
  post 'mark_as_very_urgent/:id', to: 'tasks#mark_as_very_urgent', as: 'mark_as_very_urgent'
  post 'mark_as_urgent/:id', to: 'tasks#mark_as_urgent', as: 'mark_as_urgent'
  post 'mark_as_normal/:id', to: 'tasks#mark_as_normal', as: 'mark_as_normal'
  patch 'move/:id', to: 'tasks#move'
  resources :comments, only: :destroy
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task

  validates :content, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  acts_as_list

  has_many :comments, dependent: :destroy

  validates :title, presence: true

  enum status: [:todo, :done, :cancelled]
  enum priority: [:normal, :urgent, :very_urgent]

  # PRIORITIES = ["normal", "urgent", "very urgent"]


  before_create :set_deadline, if: :deadline_nil_or_past

  def deadline_nil_or_past
    self.deadline == nil || self.deadline < Date.today
  end

  private

  def set_deadline
    self.deadline = Date.today
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def set_tasks
    @tasks = policy_scope(Task)
    @tasks_by_positions = @tasks.order(position: :asc)
    @tasks_by_deadlines = @tasks.order(deadline: :asc)
    @tasks_by_priorities = @tasks.order(priority: :desc)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    authorize @comment
    @comment.task_id = params[:task_id]
    if @comment.save
      redirect_to root_path
    else
      set_tasks
      flash[:alert] = "The content of your comment can't be blank"
      @task = Task.new
      render "tasks/index"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    authorize @comment

    @comment.destroy
    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, except: [:index, :create]
  def index
    set_tasks

    @task = Task.new
    @comment = Comment.new
  end

  def create
    @task = Task.new(task_params)
    @task.user = current_user
    set_tasks
    @comment = Comment.new

    authorize @task

    if @task.save
      respond_to do |format|
        format.html
        format.js { render :updated_todos }
      end
    else
      flash[:alert] = "Please fill all fields"
      render :index
    end
  end

  def update
    set_tasks
    @comment = Comment.new

    authorize @task
    @task.update(task_params)

    if @task.save
      respond_to do |format|
        format.html
        format.js { render :updated_todos }
      end
    else
      flash[:alert] = "Something went wrong"
      render :index
    end
  end

  def move
    authorize @task
    @task.insert_at(params[:position].to_i)
    head :ok
  end

  def mark_as_done
    authorize @task
    @task.done!
    redirect_to root_path
  end

  def mark_as_cancelled
    authorize @task
    @task.cancelled!
    redirect_to root_path
  end

  def mark_as_todo
    authorize @task
    @task.todo!
    redirect_to root_path
  end

  def mark_as_very_urgent
    authorize @task
    @task.very_urgent!
    redirect_to root_path
  end

  def mark_as_urgent
    authorize @task
    @task.urgent!
    redirect_to root_path
  end

  def mark_as_normal
    authorize @task
    @task.normal!
    redirect_to root_path
  end


  def destroy
    authorize @task

    @task.destroy
    redirect_to root_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :deadline, :priority)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
  def todo(tasks)
    tasks.where(status: 0)
  end

  def done(tasks)
    tasks.where(status: 1)
  end

  def cancelled(tasks)
    tasks.where(status: 2)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div id="navbar_todo" class="navbar-todo-poulpe">
      <%= link_to "← Log out", destroy_user_session_path, method: :delete, class: 'login-logout-btn' %>
      <p id='new_task_btn' class='new-task-btn'>add a new task</p>
  </div>
<% end %>

app/views/tasks/_done_or_cancelled_tasks.html.erb
<% tasks.each do |task| %>
  <div class="task-and-comments">
      <% if policy(task).destroy? %>
        <%= link_to "❌", task_path(task), method: :delete, remote: true, class: 'destroy-task-btn', data: {title: 'Delete task', confirm: "You are about to delete this task forever, are you sure ?"} %>
      <% end %>
    <div class="task-card">
      <div class="task-infos">
        <p class="deadline-sticker <%= "bg-success" if task.done? %> <%= "bg-warning" if task.cancelled? %>"><%= task.status %></p>
        <a class="deadline-sticker comment-sticker" data-toggle="collapse" href="#collapseComments-<%= task.id %>" role="button" aria-expanded="false" aria-controls="collapseComments-<%= task.id %>">
          <%= pluralize( task.comments.count, "comment") %>
        </a>
      </div>
      <div class="task-title-and-actions">
        <div class="task-title"><h6><%= task.title %></h6></div>
        <div class="task-actions">
          <%= link_to "back in my tasks !", mark_as_todo_path(task), method: :post, remote: true, class: 'action-btn todo-again-btn' unless task.todo? %>
        </div>
      </div>
    </div>
    <div class="collapse collapse-comments" id="collapseComments-<%= task.id %>">
      <div class="comments">
        <% if policy(Comment).create? %>
          <%= simple_form_for([ task, @comment ], remote: true) do |f| %>
            <%= f.input :content, placeholder: "add comment..." %>
            <div class="comment-submit"><%= f.submit "+" %></div>
          <% end %>
        <% end %>
        <% unless task.comments.empty? %>
          <div class="comment-cards">
            <% task.comments.each do |comment| %>
              <div class="comment-card">
                <div class="comment-content"><p><%= comment.content %></p></div>
                <%= link_to "🗑", comment_path(comment), method: :delete, remote: true %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/tasks/_done_tasks.html.erb
<% tasks.each do |task| %>
  <div class="task-and-comments">
    <div class="task-card <%= task.priority %>">
      <div class="task-infos">
        <p class="deadline-sticker bg-success">done</p>
        <a class="deadline-sticker comment-sticker" data-toggle="collapse" href="#collapseComments-<%= task.id %>" role="button" aria-expanded="false" aria-controls="collapseComments-<%= task.id %>">
          <%= pluralize( task.comments.count, "comment") %>
        </a>
      </div>
      <div class="task-title-and-actions">
        <div class="task-title"><h6><%= task.title %></h6></div>
        <div class="task-actions">
          <%= link_to "back in my tasks !", mark_as_todo_path(task), method: :post, remote: true, class: 'action-btn todo-again-btn' unless task.todo? %>

          <%#= link_to "🗑", task_path(task), method: :delete, remote: true %>
        </div>
      </div>
    </div>
    <div class="collapse collapse-comments" id="collapseComments-<%= task.id %>">
      <div class="comments">
        <% if policy(Comment).create? %>
          <%= simple_form_for([ task, @comment ], remote: true) do |f| %>
            <%= f.input :content, placeholder: "add comment..." %>
            <div class="comment-submit"><%= f.submit "+" %></div>
          <% end %>
        <% end %>
        <% unless task.comments.empty? %>
          <div class="comment-cards">
            <% task.comments.each do |comment| %>
              <div class="comment-card">
                <div class="comment-content"><p><%= comment.content %></p></div>
                <%= link_to "🗑", comment_path(comment), method: :delete, remote: true %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="collapse collapse-comments collapse-priorities" id="collapsePriority-<%= task.id %>">
      <div class="priorities">
        <%= link_to "very urgent", mark_as_very_urgent_path(task), method: :post, remote: true unless task.very_urgent? %>
        <%= link_to "urgent", mark_as_urgent_path(task), method: :post, remote: true unless task.urgent? %>
        <%= link_to "not so urgent", mark_as_normal_path(task), method: :post, remote: true unless task.normal? %>
      </div>
    </div>
  </div>
<% end %>

app/views/tasks/_draggable_tasks_todo.html.erb
<% if tasks.empty? %>
  <div class="task-and-comments">
    <div class="task-card">
      <div class="task-infos">
      </div>
      <div class="task-title-and-actions">
        <div class="task-title"><h5>Your todo list is empty !</h5></div>
        <div class="task-title"><h6>Add a new task to your list using the form just above 😀</h6></div>
        <div class="task-actions">
        </div>
      </div>
    </div>
  </div>
<% end %>

<% tasks.each do |task| %>
  <div class="task-and-comments" data-id="<%= task.id %>">
    <div class="task-card <%= task.priority %> grabbable-task">
      <div class="task-infos">
        <div class="deadline-and-calendar-btn">
          <% if (task.deadline - Date.today).to_i >= 1 %>
            <a class="deadline-sticker upcoming" data-toggle="collapse" href="#collapseDeadline-<%= task.id %>" role="button" aria-expanded="false" aria-controls="#collapseDeadline-<%= task.id %>">
              <%= pluralize((task.deadline - Date.today).to_i, "day") %> left
            </a>
          <% elsif (task.deadline - Date.today).to_i == 0 %>
            <a class="deadline-sticker today" data-toggle="collapse" href="#collapseDeadline-<%= task.id %>" role="button" aria-expanded="false" aria-controls="#collapseDeadline-<%= task.id %>">
              today
            </a>
          <% else %>
            <a class="deadline-sticker passed" data-toggle="collapse" href="#collapseDeadline-<%= task.id %>" role="button" aria-expanded="false" aria-controls="#collapseDeadline-<%= task.id %>">
              passed
            </a>
          <% end %>
        </div>
        <div class="priority-and-priorities-btn">
          <a class="deadline-sticker <%= task.priority %>" data-toggle="collapse" href="#collapsePriority-<%= task.id %>" role="button" aria-expanded="false" aria-controls="collapsePriority-<%= task.id %>">
            <%= "high priority" if task.very_urgent? %>
            <%= "urgent" if task.urgent? %>
            <%= "not urgent" if task.normal? %>
          </a>
          <div class="collapse collapse-priorities" id="collapsePriority-<%= task.id %>">
            <div class="priorities">
              <%= link_to "very urgent", mark_as_very_urgent_path(task), class: 'deadline-sticker very_urgent', method: :post, remote: true unless task.very_urgent? %>
              <%= link_to "urgent", mark_as_urgent_path(task), class: 'deadline-sticker urgent',method: :post, remote: true unless task.urgent? %>
              <%= link_to "not so urgent", mark_as_normal_path(task), class: 'deadline-sticker normal',method: :post, remote: true unless task.normal? %>
            </div>
          </div>
        </div>
        <div class="comment-and-comments-btn">
          <a class="deadline-sticker comment-sticker" data-toggle="collapse" href="#collapseComments-<%= task.id %>" role="button" aria-expanded="false" aria-controls="collapseComments-<%= task.id %>">
            <%= pluralize( task.comments.count, "comment") %>
          </a>
        </div>
      </div>
      <div class="task-title-and-actions">
        <div class="task-title"><h6><%= task.title %></h6><h6>↕</h6></div>
        <div class="task-actions">
          <%= link_to "it's done !", mark_as_done_path(task), method: :post, remote: true, class: 'action-btn done-btn' unless task.done? %>
          <%= link_to "cancel this..", mark_as_cancelled_path(task), method: :post, remote: true, class: 'action-btn cancel-btn' unless task.cancelled? %>
        </div>
      </div>
    </div>
    <div class="collapse collapse-comments" id="collapseComments-<%= task.id %>">
      <div class="comments">
        <% if policy(Comment).create? %>
          <%= simple_form_for([ task, @comment ], remote: true) do |f| %>
            <%= f.input :content, placeholder: "add comment..." %>
            <div class="comment-submit"><%= f.submit "+" %></div>
          <% end %>
        <% end %>
        <% unless task.comments.empty? %>
          <div class="comment-cards">
            <% task.comments.each do |comment| %>
              <div class="comment-card">
                <div class="comment-content"><p><%= comment.content %></p></div>
                <%= link_to "🗑", comment_path(comment), method: :delete, remote: true %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <% if policy(task).update? %>
      <div class="collapse collapse-comments" id="collapseDeadline-<%= task.id %>">
        <div class="deadline-form">
            <%= simple_form_for(task, remote: true) do |f| %>
              <%= f.input :deadline, placeholder: "#{task.deadline.strftime("%-d %B %Y")}", as: :string, required: true, input_html: {class: "datepicker"} %>
              <div class="task_submit"><%= f.submit "save" %></div>
            <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/tasks/_tasks_todo.html.erb
<% if tasks.empty? %>
  <div class="task-and-comments">
    <div class="task-card">
      <div class="task-infos">
      </div>
      <div class="task-title-and-actions">
        <div class="task-title"><h5>Your todo list is empty !</h5></div>
        <div class="task-title"><h6>Add a new task to your list using the form just above 😀</h6></div>
        <div class="task-actions">
        </div>
      </div>
    </div>
  </div>
<% end %>

<% tasks.each do |task| %>
  <div class="task-and-comments">
    <div class="task-card <%= task.priority %>">
      <div class="task-infos">
        <div class="deadline-and-calendar-btn">
          <% if (task.deadline - Date.today).to_i >= 1 %>
            <a class="deadline-sticker upcoming" data-toggle="collapse" href="#collapseDeadline-<%= task.id %>" role="button" aria-expanded="false" aria-controls="#collapseDeadline-<%= task.id %>">
              <%= pluralize((task.deadline - Date.today).to_i, "day") %> left
            </a>
          <% elsif (task.deadline - Date.today).to_i == 0 %>
            <a class="deadline-sticker today" data-toggle="collapse" href="#collapseDeadline-<%= task.id %>" role="button" aria-expanded="false" aria-controls="#collapseDeadline-<%= task.id %>">
              today
            </a>
          <% else %>
            <a class="deadline-sticker passed" data-toggle="collapse" href="#collapseDeadline-<%= task.id %>" role="button" aria-expanded="false" aria-controls="#collapseDeadline-<%= task.id %>">
              passed
            </a>
          <% end %>
        </div>
        <div class="priority-and-priorities-btn">
          <a class="deadline-sticker <%= task.priority %>" data-toggle="collapse" href="#collapsePriority-<%= task.id %>" role="button" aria-expanded="false" aria-controls="collapsePriority-<%= task.id %>">
            <%= "high priority" if task.very_urgent? %>
            <%= "urgent" if task.urgent? %>
            <%= "not urgent" if task.normal? %>
          </a>
          <div class="collapse collapse-priorities" id="collapsePriority-<%= task.id %>">
            <div class="priorities">
              <%= link_to "very urgent", mark_as_very_urgent_path(task), class: 'deadline-sticker very_urgent', method: :post, remote: true unless task.very_urgent? %>
              <%= link_to "urgent", mark_as_urgent_path(task), class: 'deadline-sticker urgent',method: :post, remote: true unless task.urgent? %>
              <%= link_to "not so urgent", mark_as_normal_path(task), class: 'deadline-sticker normal',method: :post, remote: true unless task.normal? %>
            </div>
          </div>
        </div>
        <div class="comment-and-comments-btn">
          <a class="deadline-sticker comment-sticker" data-toggle="collapse" href="#collapseComments-<%= task.id %>" role="button" aria-expanded="false" aria-controls="collapseComments-<%= task.id %>">
            <%= pluralize( task.comments.count, "comment") %>
          </a>
        </div>
      </div>
      <div class="task-title-and-actions">
        <div class="task-title"><h6><%= task.title %></h6></div>
        <div class="task-actions">
          <%= link_to "it's done !", mark_as_done_path(task), method: :post, remote: true, class: 'action-btn done-btn' unless task.done? %>
          <%= link_to "cancel this..", mark_as_cancelled_path(task), method: :post, remote: true, class: 'action-btn cancel-btn' unless task.cancelled? %>

          <%#= link_to "to do again !", mark_as_todo_path(task), method: :post, remote: true unless task.todo? %>
          <%#= link_to "🗑", task_path(task), method: :delete, remote: true %>
        </div>
      </div>
    </div>
    <div class="collapse collapse-comments" id="collapseComments-<%= task.id %>">
      <div class="comments">
        <% if policy(Comment).create? %>
          <%= simple_form_for([ task, @comment ], remote: true) do |f| %>
            <%= f.input :content, placeholder: "add comment..." %>
            <div class="comment-submit"><%= f.submit "+" %></div>
          <% end %>
        <% end %>
        <% unless task.comments.empty? %>
          <div class="comment-cards">
            <% task.comments.each do |comment| %>
              <div class="comment-card">
                <div class="comment-content"><p><%= comment.content %></p></div>
                <%= link_to "🗑", comment_path(comment), method: :delete, remote: true %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <% if policy(task).update? %>
      <div class="collapse collapse-comments" id="collapseDeadline-<%= task.id %>">
        <div class="deadline-form">
            <%= simple_form_for(task, remote: true) do |f| %>
              <%= f.input :deadline, placeholder: "#{task.deadline.strftime("%-d %B %Y")}", as: :string, required: true, input_html: {class: "datepicker"} %>
              <div class="task_submit"><%= f.submit "save" %></div>
            <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/tasks/index.html.erb
<div class="container py-5" id="main-container" data-controller="tasks">
  <div class="list-header">
    <h1>My list</h1>
  </div>
  <% if policy(Task).create? %>
    <h5 class="mt-5">Add a new task</h5>
    <%= simple_form_for(@task, remote: true) do |f| %>
      <div class="form-task-title-and-deadline">
        <%= f.input :title, placeholder: "new task..", input_html: { autofocus: true } %>
        <div class="deadline-with-calendar text-center">

          <%= f.input :deadline, label: "🗓", placeholder: "#{Date.today.strftime("%-d %b %y")}", as: :string, required: true, input_html: {class: "datepicker"} %>
        </div>
      </div>
      <%= f.input :priority, as: :radio_buttons,
                  collection_wrapper_tag: 'div',
                  collection_wrapper_class: 'category-wrapper',
                  item_wrapper_class: 'category-item',
                  input_html: {class: 'category-selector'},
                  collection: [['normal', 'normal'], ['urgent', 'urgent'], ['very_urgent', 'high priority']], label_method: :second, value_method: :first%>
      <div class="task_submit" data-action="click->tasks#refresh"><%= f.submit "+" %></div>
    <% end %>
  <% end %>
  <div class="todo-and-done-tasks">
    <div class="to-do-tasks">
      <div class="status-infos">
        <div class="list-title-and-count"><h5 class="mr-2">To do</h5> <p>(<%= todo(@tasks).count %>)</p></div>
        <div id="deadlines-and-priorities-toggle">
          <p id="by_deadlines" class="deadlines-priorities-btn">deadlines</p>
          <p id="by_positions" class="deadlines-priorities-btn active">my order</p>
          <p id="by_priorities" class="deadlines-priorities-btn">priorities</p>
        </div>
      </div>
      <div >
      </div>
        <div id="tasks_by_deadlines" class="task-cards main-lists d-none" data-target="tasks.listsDeadlines" >
          <%= render 'tasks/tasks_todo', tasks: todo(@tasks_by_deadlines) %>
        </div>
        <div id="tasks_by_positions" class="task-cards main-lists" data-controller="drag" data-drag-url="move/:id" data-target="tasks.listsPositions">
          <%= render 'tasks/draggable_tasks_todo', tasks: todo(@tasks_by_positions) %>
        </div>
        <div id="tasks_by_priorities" class="task-cards main-lists d-none" data-target="tasks.listsPriorities">
          <%= render 'tasks/tasks_todo', tasks: todo(@tasks_by_priorities) %>
        </div>

    </div>
    <div class="done-tasks">
      <div class="status-infos">
        <div class="list-title-and-count"><h5 class="mr-2">Done</h5><p>(<%= done(@tasks).count %>)</p></div>
      </div>
      <div class="task-cards">
        <%= render 'tasks/done_or_cancelled_tasks', tasks: done(@tasks) %>
      </div>
    </div>
    <div class="cancelled-tasks">
      <div class="status-infos">
        <div class="list-title-and-count"><h5 class="mr-2">Cancelled</h5><p>(<%= cancelled(@tasks).count %>)</p></div>
      </div>
      <div class="task-cards">
        <%= render 'tasks/done_or_cancelled_tasks', tasks: cancelled(@tasks) %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/update_todo.js.erb
document.getElementById('task_title').value = ''

document.getElementById("tasks_by_deadlines").innerHTML = "<%= j render(partial: 'tasks/tasks_todo', locals: { tasks: todo(@tasks_by_deadlines) } ) %>"
document.getElementById("tasks_by_priorities").innerHTML = "<%= j render(partial: 'tasks/tasks_todo', locals: { tasks: todo(@tasks_by_priorities) } ) %>"
document.getElementById("tasks_by_positions").innerHTML = "<%= j render(partial: 'tasks/draggable_tasks_todo', locals: { tasks: todo(@tasks_by_positions) } ) %>"

app/views/tasks/updated_todos.js.erb
// reset task form
document.getElementById('task_title').value = ''
document.getElementsByClassName('flatpickr-day selected')
let today = new Date();
let date = today.getDate()+'-'+(today.getMonth()+1)+'-'+today.getFullYear();
document.getElementById('task_deadline').value = date
document.getElementById('task_priority_normal').checked = true
document.getElementById('task_priority_urgent').checked = false
document.getElementById('task_priority_very_urgent').checked = false

// reload tasks lists
document.getElementById("tasks_by_deadlines").innerHTML = "<%= j render(partial: 'tasks/tasks_todo', locals: { tasks: todo(@tasks_by_deadlines) } ) %>"
document.getElementById("tasks_by_priorities").innerHTML = "<%= j render(partial: 'tasks/tasks_todo', locals: { tasks: todo(@tasks_by_priorities) } ) %>"
document.getElementById("tasks_by_positions").innerHTML = "<%= j render(partial: 'tasks/draggable_tasks_todo', locals: { tasks: todo(@tasks_by_positions) } ) %>"